{% set version = "0.14.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-insight
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/insight_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/insight/insight_{{ version }}.tar.gz
  sha256: f7a117cc65bab251fb39a67bf7891d334947179966e628fbd43eb2b49ca9c737

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('insight')"           # [not win]
    - "\"%R%\" -e \"library('insight')\""  # [win]

about:
  home: https://easystats.github.io/insight/
  license: GPL-3.0-only
  summary: "A tool to provide an easy, intuitive and consistent access to  information contained in various R models, like model formulas, model terms,  information about random effects, data that was used to fit the model or  data from response variables. 'insight' mainly revolves around two types  of functions: Functions\
    \ that find (the names of) information, starting with  'find_', and functions that get the underlying data, starting with 'get_'.  The package has a consistent syntax and works with many different model  objects, where otherwise functions to access these information are missing."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: insight
# Type: Package
# Title: Easy Access to Model Information for Various Model Objects
# Description: A tool to provide an easy, intuitive and consistent access to  information contained in various R models, like model formulas, model terms,  information about random effects, data that was used to fit the model or  data from response variables. 'insight' mainly revolves around two types  of functions: Functions that find (the names of) information, starting with  'find_', and functions that get the underlying data, starting with 'get_'.  The package has a consistent syntax and works with many different model  objects, where otherwise functions to access these information are missing.
# Version: 0.5.0
# Date: 2019-09-04
# Authors@R: c(person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206")), person("Dominique", "Makowski", role = c("aut", "ctb"), email = "dom.makowski@gmail.com", comment = c(ORCID = "0000-0001-5375-9967")), person("Indrajeet", "Patil", role = c("aut", "ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531")), person("Philip", "Waggoner", role = c("aut", "ctb"), email = "philip.waggoner@gmail.com", comment = c(ORCID = "0000-0002-7825-7573")))
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# License: GPL-3
# URL: https://easystats.github.io/insight/
# BugReports: https://github.com/easystats/insight/issues
# Depends: R (>= 3.0)
# Imports: methods, stats, utils
# Suggests: AER, afex, aod, BayesFactor, bayestestR, betareg, biglm, blme, brms, censReg, crch, coxme, covr, estimatr, feisr, gam, gamm4, gamlss, gbm, gee, geepack, GLMMadaptive, glmmTMB, gmnl, HRQoL, httr, lfe, logistf, MASS, MCMCglmm, mlogit, multgee, lme4, mgcv, nnet, nlme, ordinal, panelr, plm, pscl, quantreg, rms, robust, robustbase, robustlmm, rstanarm, rstudioapi, speedglm, splines, survey, survival, truncreg, testthat, VGAM, knitr, rmarkdown, spelling
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-09-04 08:06:59 UTC; mail
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>), Dominique Makowski [aut, ctb] (<https://orcid.org/0000-0001-5375-9967>), Indrajeet Patil [aut, ctb] (<https://orcid.org/0000-0003-1995-6531>), Philip Waggoner [aut, ctb] (<https://orcid.org/0000-0002-7825-7573>)
# Repository: CRAN
# Date/Publication: 2019-09-07 16:40:03 UTC
