travis:
  secure:
    BINSTAR_TOKEN: alyvULN46STnVYxSPysvK2T6RjCkw/o2mquadkrIciO7XebyNWxV6GTx02Z4TZDW4Osx8J6gEmWXMTwxB292tWN4FeK1ULUZloSTHMYS/Wn4VselNGuRhZE/gZ8UXmIWUBUZuXCc/TZ8wDSNTYTOaCLszVNfHsOuJjYHjhulH1ljaVaybCs6pWSrLRqMOTd+/zYVzNuYlk3AjozVMd4wyHIcshzeuGgRI1yYTePCHirU3HGVRniu5QO3iZRsV0VX3e1yf0qKnnij1Gx+CBwUPlnF091GsTUcY+Gav8GZod7Svs/Wv5f4pcKMAB2oUIC4kp3eKj7VLP7eixqwqZ8DGGS2bXtkdUQ2B/B1pbLG4t7MSrwbupqXHyR+fT6Um4Yr7owuvrsbwIfaeej9p5WM94mklekPHNFFRLO3Ozgxx+TkofN9rCEzwea0QrPLhDeRtLos8qnZ/otksZ9YXT+p4WGMST/D0RI/bFhQe7kvwIJnh364YYWylrrtd2yW9oTEmEbebnQivVDl4tKSlgOg9S6GdoVsb1BCENukvJOMDAB/Q0P4bkEfZDRhYNkA9svSAJ1Mk93SE4iZUYPPn8P5sUwK+A9sbXmquUvzSfdeBVc4g7PIF3R5XRlJgBJHqKEedg+UvzCkJYAXQYOb+bCJdbl0JDQP9x7D64tD52S5d1U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
