appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IN1XyzZO177Qu6kso+RqvdbG4J+daSGOANKpZwjF7qzue0fcWZb0TtDwpoGRJvOoRf8F7dY+7wTCbZZfDsjEYiQMTji/PbF+VAjgl18zqprDIvgVM2hBphfCOnTmbtCJuPyPWmJpmt9f3/duXq1ig7eGiiiS76Cmfm32pbcZBzAqesmRRPY0bSQHHmln0NXG8zoLA1aZpi7C4NsicPTOF58uVU4S8cLWTj/8GGiS0ZcYw+ZjXITJrRG1sCVq2XDVal8jFBN9CvuHM8/RBrTn+nv7GzsVHUf5gBeBK2+Tjsz7AFHgg9ojCI6FTnR/BvRMQfnrNoZLKLkNViKGwQdBxDZ9/0YL/e8N92QDlcLBw1XTazPBcbx2FHmrd7JTx8G5LIk8lkDqcgkATtzjvaorG80XMMJ7s3xDzpwkm6fGxY7YJ+aiIsbd4ST6tQ092A0RXXoCEOw+EpO/syJZrUVe1UG4JLbXiTEPYhUhmh8pgh++w3slPFRLzYoo8nbpJ74tIPVtUpD29qO9NXysMc4RFzzLifQC31JD68bKLlkOpcZcUQstsiQd+p2Y3U00hQgfC1Icth2J+7cM/lMflQS6IiBiD5yjjvI83JkAU6aPHnKvZLli2qGSxT6j1ntBLPS7mvi0qxc2TqyeMqFvTL9ScfnIwrAzPdY785fle2dgZSI=
